Repository Team-Puzzling/Puzzling_Server, pull requests merged in 2023-07, with the labels that each got.

#3 [SETTING] common 파일 및 에러 처리 관련 파일 세팅
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/advice/ControllerExceptionAdvice.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/JpaAuditingConfig.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/TimezoneConfig.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/entity/BaseTimeEntity.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/exception/BadRequestException.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/exception/BaseException.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ApiResponse.java
Labels: 🐼 예슬 🐼, ⚙️SETTING⚙️

#6 #5 [FEAT] 유저, 프로젝트, 회고, 템플릿 Entity 설계
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/SocialPlatform.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/domain/Member.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/domain/Project.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/domain/UserProject.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/domain/Review.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/domain/Review5F.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/domain/ReviewAAR.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/domain/ReviewTIL.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/domain/ReviewTemplate.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#8 #7 [FEAT] 프로젝트 초대코드 유효성 검사 API 개발
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectVerifyResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/ProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/ProjectService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/advice/ControllerExceptionAdvice.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/exception/NotFoundException.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ApiResponse.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ErrorStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
  puzzlingServer/src/test/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImplTest.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#10 #9 [FEAT] 진행 중인 프로젝트 리스트 조회 API 개발
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/domain/UserProject.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/ProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/UserProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/ProjectService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ApiResponse.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#11 #4 [FEAT] 카카오 소셜 로그인 및 토큰 재발급 API 구현
  .idea/.gitignore
  .idea/.name
  .idea/Puzzling_Server.iml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  puzzlingServer/build.gradle
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/SocialPlatform.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/controller/AuthController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/dto/Request/AuthRequestDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/dto/Response/AuthResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/dto/Response/AuthTokenResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/dto/SocialInfoDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/AuthService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/Impl/AuthServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/KakaoAuthService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/repository/MemberRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/UserProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/advice/ControllerExceptionAdvice.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/SecurityConfig.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/jwt/JwtAuthenticationEntryPoint.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/jwt/JwtAuthenticationFilter.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/jwt/JwtExceptionType.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/jwt/JwtTokenProvider.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/jwt/UserAuthentication.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/exception/UnAuthorizedException.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ErrorStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/util/MemberUtil.java
Labels: 🐥 홍준 🐥, ✨FEAT✨

#15 #12 [FEAT] 회고 템플릿 목록 조회 API 구현
  .idea/gradle.xml
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/ReviewTemplateGetResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/ReviewTemplateRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐥 홍준 🐥, ✨FEAT✨

#17 #14 [FEAT] 개인 대시보드 퍼즐 조회 API
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/Impl/AuthServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/KakaoAuthService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectMyPuzzleObjectDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectOwnPuzzleResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/PuzzleObjectDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/ProjectService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/repository/ReviewRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/advice/ControllerExceptionAdvice.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ErrorStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#19 #16 [FEAT] TIL 템플릿 회고 작성 API
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/Impl/AuthServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/domain/UserProject.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/UserProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/domain/Review.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/request/ReviewTILRequestDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/ReviewTemplateGetResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/repository/ReviewRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/ReviewTILRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/ReviewTemplateRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/advice/ControllerExceptionAdvice.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐥 홍준 🐥, ✨FEAT✨

#22 #18 [FEAT] 팀 대시보드 퍼즐 조회 API
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/Impl/AuthServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectTeamPuzzleResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/TeamPuzzleObjectDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/UserProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/ProjectService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/repository/ReviewRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/advice/ControllerExceptionAdvice.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ErrorStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/util/MemberUtil.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#24 #13 [FEAT] 이전 회고 템플릿 형식 조회 성공
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectMyPuzzleObjectDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/UserProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/ProjectService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/ReviewPreviousTemplateResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#26 #23 [FEAT] ARR템플릿 회고 작성 API개발 완료
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/request/ReviewAARRequestDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/ReviewARRRepository.java
Labels: 🐥 홍준 🐥, ✨FEAT✨

#28 #25 [FEAT] ACTIONPLAN 내용 조회 API 개발
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/ReviewActionPlanResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/repository/ReviewRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/Review5FRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/ReviewAARRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/ReviewTILRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/domain/Review5F.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#31 #27 [FEAT] 프로젝트 등록 API 개발
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/request/ProjectRegisterRequestDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectRegisterResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/ProjectService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/ReviewAARRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/Repository/ReviewARRRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐥 홍준 🐥, ✨FEAT✨

#33 #32 [FEAT] 프로젝트 참여 API
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/request/ProjectJoinRequestDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectJoinResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/UserProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/ProjectService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐥 홍준 🐥, ✨FEAT✨

#36 #29 [FEAT] 팀원 회고 랭킹 조회 API 개발
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/domain/UserProject.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectTeamRankResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/repository/UserProjectRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/ProjectService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/util/MemberUtil.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#39 #38 [FEAT] 해당 프로젝트 내 회고 리스트 조회 API
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/MyReviewProjectResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
Labels: 🐥 홍준 🐥, ✨FEAT✨

#42 #30 [FEAT] 팀원 회고 상황 조회 API
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/domain/UserProject.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/request/ProjectRegisterRequestDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/request/ReviewTILRequestDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/ReviewTeamStatusResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/ReviewWriterObjectDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/repository/ReviewRepository.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/advice/ControllerExceptionAdvice.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/config/jwt/JwtTokenProvider.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ErrorStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/util/DateUtil.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#44 #43 [FIX] 프로젝트 코드 반환 기능
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectRegisterResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
Labels: 🐥 홍준 🐥, ✨FEAT✨

#45 #37 [FEAT] 기간에 따른 회고 상세 조회 API
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/ReviewContentObjectDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/ReviewDetailResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/strategy/AARReviewTemplateStrategy.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/strategy/FiveFReviewTemplateStrategy.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/strategy/ReviewTemplateStrategy.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/template/strategy/TILReviewTemplateStrategy.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/SuccessStatus.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/util/DateUtil.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#47 #46 [FIX] 개인 대시보드 퍼즐판에서 에셋 이름 버그 수정
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
Labels: 🐼 예슬 🐼, 🔨FIX🔨

#49 #48 [Refactor] Auth 관련 에러처리 리팩토링
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/SocialPlatform.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/Impl/AuthServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/common/response/ErrorStatus.java
Labels: 🐥 홍준 🐥, 🐼 예슬 🐼, ♻️ REFACTOR♻️ 

#54 #53 [FIX] 팀원 회고 상황 조회 API에서 빈 배열 null로 처리
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
Labels: 🐼 예슬 🐼, 🔨FIX🔨

#56 #52 [REFACTOR] Review 관련 API response 리팩토링
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
Labels: 🐼 예슬 🐼, ♻️ REFACTOR♻️ 

#57 #52 [REFACTOR] 퍼즐 에셋 이름 소문자로 변경
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
Labels: 🐼 예슬 🐼, ✅ CHORE ✅ 

#59 #58 [FIX] 개인 & 팀 대시보드 퍼즐판 로직 수정
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectOwnPuzzleResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectTeamPuzzleResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/repository/ReviewRepository.java
Labels: 🐼 예슬 🐼, 🔨FIX🔨

#61 #60 [FIX] 프로젝트 등록시 프로젝트Id반환
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/workspace.xml
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/controller/ProjectController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/dto/response/ProjectRegisterResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
Labels: 🐥 홍준 🐥, 🔨FIX🔨

#63 #62 [FEAT] 개인 및 팀 대시보드 퍼즐판 빈 퍼즐까지 내려주는 로직 구현
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
Labels: 🐼 예슬 🐼, ✨FEAT✨

#66 #65 [REFACTOR] 리뷰 작성 시, 프로젝트 이름 response body로 내려주기
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/controller/ReviewController.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/dto/response/ReviewPostResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/Impl/ReviewServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/service/ReviewService.java
Labels: 🐼 예슬 🐼, ♻️ REFACTOR ♻️ 

#68 #67 [REFACTOR] 로그인 반환값 수정
  .idea/.gitignore
  .idea/Puzzling_Server.iml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/dto/Response/AuthResponseDto.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/member/auth/service/Impl/AuthServiceImpl.java
Labels: 🐥 홍준 🐥, ♻️ REFACTOR ♻️ 

#70 #69 [REFACTOR] 팀 대시보드에서 팀 이름과 퍼즐 개수 수정
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
Labels: 🐼 예슬 🐼, ♻️ REFACTOR ♻️ 

#72 #71 [FIX] 개인 대시보드에서 hasReview값 로직 수정
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/repository/ReviewRepository.java
Labels: 🐼 예슬 🐼, 🔨 FIX 🔨

#74 #73 [FIX] 개인 대시보드에서 나오는 닉네임은 프로젝트 내 닉네임으로 수정
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/review/repository/ReviewRepository.java
Labels: 🐼 예슬 🐼, 🔨 FIX 🔨

#76 #75 [FIX] 팀 대시보드 퍼즐판에서 노란 퍼즐 내려주는 케이스 로직 수정
  puzzlingServer/src/main/java/com/puzzling/puzzlingServer/api/project/service/Impl/ProjectServiceImpl.java
Labels: 🐼 예슬 🐼, 🔨 FIX 🔨
